Ddoc

$(D_S WindowsでのDのデバッグ,

$(P Microsoft Windows デバッガ $(D $(DMDDIR)\windows\bin\windbg.exe) は、C++ 用のデバッガですが、
D のプログラムをデバッグすることも可能です。dmdコンパイラに同梱されている以外のバージョンの
$(D windbg.exe) は、D ではうまく動かない可能性があります。
（他に、Jascha Wetzel の $(LINK2 http://ddbg.mainia.de/releases.html, Ddbg for Windows)
もDのデバッガとして使用可能です。）
)

$(P デバッグ情報を用意するには、コンパイル時に
$(B -gc) スイッチを指定します:
)

$(CONSOLE
dmd myprogram -gc
)

$(P このプログラムをデバッグするには:
)

$(CONSOLE
windbg myprogram args...
)

$(P
$(D args...) は myprogram.exe に渡すコマンド引数です。
)

$(P デバッガが起動したら、コマンドウインドウに以下のコマンドを入力すると:)

$(CONSOLE
g _Dmain
)

$(P プログラムが $(D main()) の頭まで実行されます。
その後は、$(B F10) を１回押すたびにコードを１行ずつ
ステップ実行していくことができます。)

$(P 基本コマンド:)

$(DL

$(DT F5)
$(DD ブレークポイント、例外発生、プログラム終了のどれかが起きるまで実行)

$(DT F7)
$(DD カーソル位置まで実行)

$(DT F8)
$(DD 関数呼び出しの中に入るステップ実行)

$(DT F10)
$(DD 関数呼び出しはスキップするステップ実行)
)

$(P $(B windbg) に関するきちんと情報については、
$(D $(DMDDIR)\windows\bin\windbg.hlp) を参照してください。
)

$(COMMENT
<h2>Sample Debug Session</h2>

$(P This is a walkthrough of a typical debugging session. Given the program:)

----------
import std.stdio;

class Foo
{
    int x;
}

int main()
{
    Foo p;
    bar(p);
}

void bar(Foo p)
{
    abc(p);
}

void abc(Foo p)
{
    p.x++;
}
---------

$(P It is compiled and run with the following commands:)

$(CONSOLE
C:\bug>dmd bug -g
\dm\bin\link bug,,,user32+kernel32/co/noi;

C:\bug>bug
Error: Access Violation

C:\bug>
)

$(P It's obviously got a bug, so fire up the debugger with:)

$(CONSOLE
C:\bug>windbg bug.exe
)

$(P and the debugger window comes up:)

<img src="foo.bmp">

$(P Advance to the beginning of $(D main()) by entering $(D g _Dmain):)

<img src="windbg2.gif">

$(P now were at the beginning of main(). The upper left black window shows
the console output so far, the middle window shows the current location
and next instruction (the $(D xor)), The lower right window shows the
current location in the source code, highlighted in yellow.)

$(P In order to run until the exception happens, use the $(D g) command:)

<img src="windbg3.gif">

$(P The $(D First chance exception) says an exception was thrown. The
lower right window now shows the line on which the exception happened
highlighted in yellow.)

$(P Now click on the [Window] menu and Select [Calls]:)

<img src="windbg4.gif">

$(P and a window will appear showing the call stack:)

<img src="windbg6.gif">

$(P Clicking on the [Disassembly] command brings up
the Disassembly window where the instruction that faulted is highlighted
in yellow. Clicking on the [Registers] command brings up
the register window, where EAX holds the value 00000000.)

<img src="windbg7.gif">

$(P The trouble is clearly that $(D p) is $(D null). Fix it by allocating
an instance for $(D p):)

----------
import std.stdio;

class Foo
{
    int x;
}

int main()
{
    Foo p = new Foo;   // the fix
    bar(p);
}

void bar(Foo p)
{
    abc(p);
}

void abc(Foo p)
{
    p.x++;
}
---------

$(P and it should now compile and run without error.)
)

)

Macros:
	TITLE=WinDbg デバッガ
	WIKI=Windbg
	CATEGORY_DOWNLOAD=$0

